### ISSUE TITLE
How to mock service correctly?

### ISSUE THREAD

**Issue by olha-bastieieva** [christophd/citrus-samples#10]
Hi,
I want to mock different services in my test case, with validation of received request and response with certain payload. For now I tried with small test client which sends request to my Citrus http-server, receives response and sends back response with received payload.
When I'm using static-response-adapter, seems that everything works correctly. But when I'm trying to use http-server methods in my test case, test case fails at the last step (receive response from client) with error 

> [Fatal Error] :-1 :-1 : Premature end of file.

Could you please advice how should I set up my mocked service correctly?

**My failed test case is:**

        @CitrusTest
        public void testRequest2(){
            http()
                    .client("sandboxClient")
                    .get("/");

            http()
                    .server("sandboxServer2")
                    .receive()
                    .get();
            http()
                    .server("sandboxServer2")
                    .send()
                    .response(HttpStatus.OK)
                    .payload("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                            "            <message>\n" +
                            "                <body>\n" +
                            "                    <StartResponse xmlns=\"http://www.revenue.ie/schemas/customs/evr/processes/v1/processes/core/MSRefProRata/MSRefProRata\">WTF</StartResponse>\n" +
                            "                </body>\n" +
                            "            </message>")
                    .contentType("application/xml");

            http()
                    .client("sandboxClient")
                    .response()
                    .messageType("xml")
                    .payload("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                            "            <message>\n" +
                            "                <body>\n" +
                            "                    <StartResponse xmlns=\"http://www.revenue.ie/schemas/customs/evr/processes/v1/processes/core/MSRefProRata/MSRefProRata\">WTF</StartResponse>\n" +
                            "                </body>\n" +
                            "            </message>");

    }
Configured client and server:
  
     <citrus-http:server id="sandboxServer2"

                        resource-base="test1/"
                        port="8080"
                        auto-start="true"/>
    <citrus-http:client id="sandboxClient"
                        request-url="http://localhost:9090/sandbox_client.php"
                        request-method="GET"
                        content-type="application/xml"
                        timeout="60000"/>`

**Working test case:**

    @CitrusTest
    public void testRequest1() {
        http()
                .client("sandboxClient")
                .get("/");

        http()
                .client("sandboxClient")
                .response()
                .messageType("xml")
                .payload("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                        "            <message>\n" +
                        "                <body>\n" +
                        "                    <StartResponse xmlns=\"http://www.revenue.ie/schemas/customs/evr/processes/v1/processes/core/MSRefProRata/MSRefProRata\">WTF</StartResponse>\n" +
                        "                </body>\n" +
                        "            </message>");

    } 

and declared adapter:

    <citrus:static-response-adapter id="sandboxEndpointAdapter">
        <citrus:payload>
            <![CDATA[
            <?xml version="1.0" encoding="UTF-8"?>
            <message>
                <body>
                    <StartResponse xmlns="http://www.revenue.ie/schemas/customs/evr/processes/v1/processes/core/MSRefProRata/MSRefProRata">WTF</StartResponse>
                </body>
            </message>
            ]]>
        </citrus:payload>
    </citrus:static-response-adapter>`

**Comment by olha-bastieieva** [comment]
attached failing test case log
[test_log.txt](https://github.com/christophd/citrus-samples/files/583677/test_log.txt)

**Comment by christophd** [comment]
You have to add a fork(true) option to the client("sandboxClient").send() action because the Http protocol is synchronous and otherwise the client will wait for a response and block the rest of the test case execution.

**Comment by olha-bastieieva** [comment]
Thanks, with fork(true) option it works (also I had to add timeout parameter to server)

**Comment by viharnaik** [comment]
I almost spent 2 days trying to solve this issue. @christophd  Could you please add this into the Citrus Bible ?

**Comment by sdenel** [comment]
I spent a few hours on it too. Some documentation might help! Thanks a lot!
