### ISSUE TITLE
Could not resolve dependencies for samples project 

### ISSUE THREAD

**Issue by svemula1** [christophd/citrus-samples#11]
Failed to execute goal on project citrus-bakery-web: Could not resolve dependencies for project com.consol.citrus.samples:citrus-bakery-web:war:2.6.3-SNAPSHOT

Any help?? I just followed the instructions

**Comment by christophd** [comment]
Seems like you are having problems to download some Maven dependencies. Can you please provide the full Maven error message?

Where exactly in the instructions are you right now?

**Comment by dmoll1974** [comment]
I have the same, this is the complete error

[ERROR] Failed to execute goal on project citrus-bakery-web: Could not resolve dependencies for project com.consol.citrus.samples:citrus-bakery-web:war:2.6.3-SNAPSHOT: The following artifacts could not be resolved: com.consol.c
itrus:citrus-core:jar:2.6.3-SNAPSHOT, com.consol.citrus:citrus-java-dsl:jar:2.6.3-SNAPSHOT, com.consol.citrus:citrus-http:jar:2.6.3-SNAPSHOT, com.consol.citrus:citrus-ws:jar:2.6.3-SNAPSHOT, com.consol.citrus:citrus-jms:jar:2.6.
3-SNAPSHOT: Could not find artifact com.consol.citrus:citrus-core:jar:2.6.3-SNAPSHOT -> [Help 1]

**Comment by christophd** [comment]
The 2.6.3-SNAPSHOT version of Citrus is available here:

    <repository>
      <id>consol-labs-snapshots</id>
      <url>http://labs.consol.de/maven/snapshots-repository/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>

The jar files should be automatically downloaded from that repository. The repository is defined in the citrus-samples parent Maven POM. Maybe you need to add the consol-labs-snapshots repo to your company's Maven repository manager (e.g. Nexus)?

**Comment by christophd** [comment]
Ah, now I see why it is not working. The citrus-samples parent Maven POM defines the consol-labs-snapshots repo, but the bakery-sample Maven project is not inheriting from that parent POM.

So we need to add the consol-labs-snapshots repo definition to the bakery sample POM explicitly.

**Comment by dmoll1974** [comment]
Yes that worked :-) Thanks
