### ISSUE TITLE
Missed info about oxm sample

### ISSUE THREAD

**Issue by olha-bastieieva** [christophd/citrus-samples#3]
At the https://github.com/christophd/citrus-samples/tree/master/sample-oxm page and at the online help some important info is missed:
1. together with adding marshaller bean we need to add into citrus-context.xml file in the xsi:schemaLocation section this info:
"http://www.springframework.org/schema/oxm http://www.springframework.org/schema/oxm/spring-oxm-4.3.xsd"
2. it would be nice to have info that except the message object class we also need ObjectFactory class at the model package (I'm novice in java so for now I simply copied it into my project from this sample to have my test working. But I still don't understand the logic)

**Comment by christophd** [comment]
The ObjectFactory class can be used to create objects that are part of the marshaller instance. But it should be optional.
