### ISSUE TITLE
Its possible to send payload to different Endpoints using Endpoints ID : 

### ISSUE THREAD

**Issue by SaiedTrefi** [christophd/citrus-samples#4]
I  am trying to send payload to end point using the Id of the end point which specified in the  citrus-conext.xml : (using todo-xml sample): 

    <citrus-http:client id="todoListClient"
       request-url="http://localhost:8080"/>

1-i want to send the payload using the Id , like this code below  but it doesn't work :
 
     http()
                .send("todoListClient")
                .post("/todolist")
                .contentType("application/xml")
                .payload(new ClassPathResource("templates/todo.xml"));

2-I would like to have information if its possible to send data to different end-points using the ids for each one in the test case ? , for the example in the context:xl file add one more end-point 

    <citrus-http:client id="todoListClient"
        request-url="http://localhost:8080"/>
    <citrus-http:client id="nexID"
       request-url="http://localhost:8888"/>

Then in the test case i send to each end point like in the code below : 

      http()
                .send("todoListClient")
                .post("/todolist")
                .contentType("application/xml")
                .payload(new ClassPathResource("templates/todo.xml"));

     http()
                .send("nextID")
                .post("/todolist")
                .contentType("application/xml")
                .payload(new ClassPathResource("templates/saied.xml"));

**Comment by christophd** [comment]
The answer is Yes. It is possible to use multiple client components with different endpoint URIs.

Please provide error messages and stack trace information so I can see what is happening.

**Comment by olha-bastieieva** [comment]
If you want to connect to different http-clients, you need to use @Qualifier annotation. For your http-clients it may look like:
@Autowired
    @Qualifier("todoListClient")
    public HttpClient todoListClient;

    @Autowired
    @Qualifier("nextID")
    public HttpClient nextID;

**Comment by christophd** [comment]
Totally right, but I think @SaiedTrefi is not using autowiring in his example. He references the client endpoint components by their name as String in send() methods. 

So I still need to see the error information and stack trace.

**Comment by SaiedTrefi** [comment]
Thank you @olha-bastieieva  and @christophd  for reply : 
Yes you write @christophd : 

basically i am trying to use this approach :  

 @Test
   @CitrusTest
public void testNextEndpoint (){
        send("http://localhost:8080/todolist/")
          .payload(new ClassPathResource("templates/todo.xml"));
}
    @Test
    @CitrusTest
    public void nexteEndpoint(){
        send("se")
                .payload(new ClassPathResource("templates/todo.xml"));
 }

while i have two Endpoint in my file like this : 
    <citrus-http:client id="todoListClient"
                        request-url="http://localhost:8080/todolist/"/>
    <citrus-http:client id="se"
                        request-url="http://studentprofile.eu/"/>

and i get the flowing error : 
14:01:12,388 INFO  tContextBootstrapper| Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@4671e53b, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@2db7a79b, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@6950e31, org.springframework.test.context.support.DirtiesContextTestExecutionListener@b7dd107]
[TestNG] Running:
  C:\Users\saied.trefi\.IdeaIC2016.2\system\temp-testng-customsuite.xml
14:01:12,809 INFO  icApplicationContext| Refreshing org.springframework.context.support.GenericApplicationContext@33b37288: startup date [Fri Nov 04 14:01:12 EET 2016]; root of context hierarchy
14:01:12,934 INFO         citrus.Citrus| Unable to locate Citrus application properties
14:01:12,996 INFO  BeanDefinitionReader| Loading XML bean definitions from URL [file:/C:/Users/saied.trefi/sample-xml/target/test-classes/citrus-context.xml]
14:01:13,392 DEBUG BeanDefinitionReader| Loaded 7 bean definitions from location pattern [classpath*:citrus-context.xml]
14:01:13,793 DEBUG .XsdSchemaRepository| Loading XSD schema resource citrus-http-message.xsd
14:01:13,965 ERROR t.TestContextManager| Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@6950e31] to prepare test instance [com.consol.citrus.samples.todolist.TodoListIT@1786f9d5]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.consol.citrus.samples.todolist.TodoListIT': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.consol.citrus.http.client.HttpClient com.consol.citrus.samples.todolist.TodoListIT.todoClient; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.consol.citrus.http.client.HttpClient] is defined: expected single matching bean but found 2: todoListClient,se

**Comment by SaiedTrefi** [comment]
@christophd 
Sorry , i delete my last issue , it was syntax error , in my test case :) 

Thanks @olha-bastieieva  @christophd
