### ISSUE TITLE
Data dictionary - is it possible to define different amount of array items?

### ISSUE THREAD

**Issue by olha-bastieieva** [christophd/citrus-samples#7]
Hi,
I have payload template like:
    {
    "title": "New title",
    "body": "Issue is present",
    "labels": ["test"]
    }

and in my test case I want to use dictionary to re-assign "labels" value with another amount of items (dictionary:

    <citrus:json-data-dictionary id="jsonCreateIssueGitHubDictionary" global-scope="true">
        <citrus:mappings>
            <citrus:mapping path="title" value="citrus:concat('Dictionary1_', citrus:randomNumber(4))"/>
            <citrus:mapping path="body" value="${body}"/>
            <citrus:mapping path="labels[0]" value="dictionary1.test"/>
            <citrus:mapping path="labels[1]" value="dictionary1.bug"/>
            <citrus:mapping path="labels[2]" value="dictionary1.feature"/>
        </citrus:mappings>
    </citrus:json-data-dictionary>`

However during test case execution only one label is being assigned (so "test" from template is being replaced with "dictionary1.test"). Is it possible to have several items added without adding their placeholders into template?

**Comment by christophd** [comment]
No that is not possible right now but there is a feature request for that see https://github.com/christophd/citrus/issues/69
