### ISSUE TITLE
Is there some way to write the template in Java ? 

### ISSUE THREAD

**Issue by SaiedTrefi** [christophd/citrus-samples#9]
In the user guide the example about Template Cheaper 13 , show how can create template using Xml then call the template in Java , i am wondering if  there some way to create the template in Java (the same way as behavior ) then apply this template in any test case(as a test) ?

**Comment by christophd** [comment]
The template mechanism in Java DSL is the behavior. This is the exact equivalent solution to templates in XML

**Comment by SaiedTrefi** [comment]
Ok can you implemented (@test / @citrustest) inside the behaviour , and call it in other test method  ?

**Comment by christophd** [comment]
See this samples here:

https://github.com/christophd/citrus/blob/master/modules/citrus-java-dsl/src/test/java/com/consol/citrus/dsl/design/ApplyTestDesignBehaviorTest.java

https://github.com/christophd/citrus/blob/master/modules/citrus-java-dsl/src/test/java/com/consol/citrus/dsl/runner/ApplyTestRunnerBehaviorTest.java

I should add detailed description in user guide, thanks for pointing to it

**Comment by SaiedTrefi** [comment]
Ok thanks , close  issue please
